### ISSUE TITLE
[BUG] UVtools shows pixels missing from layers creating islands even though the original file is fine

### ISSUE THREAD

**Issue by Klindel** [sn4k3/UVtools#142]
Layer 356
![image](https://user-images.githubusercontent.com/1211087/107838064-f8950f00-6d58-11eb-9342-84f1554411e7.png)

Layer 355
![image](https://user-images.githubusercontent.com/1211087/107838076-06e32b00-6d59-11eb-9401-405c28754268.png)

Layer 354
![image](https://user-images.githubusercontent.com/1211087/107838079-0fd3fc80-6d59-11eb-8643-f7fd4b04dbc6.png)
Here is the same layers in Chitubox
![image](https://user-images.githubusercontent.com/1211087/107838142-5164a780-6d59-11eb-805e-138d39656d93.png)

 The supports are continuous but UVtools says they're not

**Comment by sn4k3** [comment]
I see a missing land on between. Maybe chitubox bug? You can't have such precision on the 3D visualizer, but check the 2D layers at chitubox preview

![image](https://user-images.githubusercontent.com/113281/107838417-b215d380-6d9d-11eb-8ed0-99044badcff3.png)

**Comment by Daoenti** [comment]
This is a known bug in Chitubox, it's been reported for versions and versions and they apparently still haven't fixed it.  So this happens when Chitubox slices places that have multiple supports stacked in one spot.  Sometimes it will glitch and end up with a slice that only has three or four individual pixels of the support.  When you run the repair in UVtools it removes those single pixels and leaves you with a blank slice in the support.

It's 100% a Chitubox problem and the reason I switched to Lychee.

**Comment by sn4k3** [comment]
UVtools only remove such pixels if they are islands OR if you run noise removal >= 1

**Comment by Klindel** [comment]
Thanks! I wasn't aware of the issue, will try something else
