### ISSUE TITLE
[FEATURE REQUEST] Cursor coordinates

### ISSUE THREAD

**Issue by MartinLunn** [sn4k3/UVtools#186]
## Is your feature request related to a problem? Please describe

Background:
Workflow:
1. Manual support in chitubox
2. Slice, and save to file
3. Open with UVTools and detect problems
4. For fixing islands, I try to locate where the island is on the 3d model to determine if fixing the island would adjust the part's look or function before making any changes. This is useful to me because if the island is on a support structure I can be very heavy handed, or if it's on a detailed and smooth section like a face, I want to be as subtle as I can be.

Problem:
When I click on an automatically detected issue from the list:

![image](https://user-images.githubusercontent.com/10377451/115846282-bc80c900-a3ef-11eb-9651-31c1d6f48498.png)

It brings me to a zoomed in view so that I can see the problem. This is great.

Actual Problem:
I find it very frustrating when I'm trying to locate where that issue is once I zoom out. Further, when there are multiple issues very close together, it's difficult to determine which one is being detected.

## Describe the solution you'd like
1. Provide current coordinates in the 2d view of the cursor

OR

2. Have an option to highlight the current issue

or both :)

Possible Location:

![image](https://user-images.githubusercontent.com/10377451/115847096-96a7f400-a3f0-11eb-86c0-965698f83bc0.png)

## Describe alternatives you've considered
It's really frustrating to have to maintain my mouse on the issue while zooming out. If I zoom out too much, the "zoom out while centred on the cursor" feature doesn't work.

**Comment by sn4k3** [comment]
That resin trap example is bad, as they are so small and are probably fake traps.
Selected issues have a slight different color which you can configure, but the solution to your problem is: 
![image](https://user-images.githubusercontent.com/113281/115892787-68a5cc80-a44f-11eb-8172-6f6ce4e0e40c.png)

You can also disable this:
![image](https://user-images.githubusercontent.com/113281/115892920-8ecb6c80-a44f-11eb-917c-bc60154f1eee.png)
OR hold ALT while you select a issue, that will invert that setting, which will center on issue without zoom

**Comment by MartinLunn** [comment]
Thanks for the awesome reply, I'll give it a shot!
