### ISSUE TITLE
[BUG] Not functioning feature of non lifting sequence for layers in same Z - Anycubic Photon Mono SE printer

### ISSUE THREAD

**Issue by IvanIstur** [sn4k3/UVtools#228]
## System
 - OS: Windows 10 x64 
 - Slicer: UVTools 2.13.3 x64
 - Printer: Anycubic Photon Mono SE

## Describe the bug
When creating an Exposure Time Finder for Anycubic Photon Mono SE printer, and selected the feature 'Do not perform the lifting sequence fo layers with same Z positioning' , the final file do not operate in the printer as indicated although should be. E.g: if 6 objects of 5mm high are configured with 0.01 mm layer and UVTools calculate the printing time in 50 min with the feature of not lifting on, the printer performs for each object the lifting sequence instead and rises the time up to 4 hours.

## To Reproduce
1. Open UVTools
2. Open a Photon Slice file (.pwms format)
3. Calibration > 'Exposure Time Finder'
4. Create the Exposure Time Finder profile
5. Select 'Multiple exposures' tickbox -> Select 'Enable - For advanced users only!' tickbox -> Select 'Do not perform the lifting sequence fo layers with same Z positioning' tickbox -> Select 'Also set light-off delay to zero' tickbox
6. Continue with generation of exposure finder
7. Send file created to Anycubic Photon Mono SE printer

## Expected behavior
Areas with same Z value shall be exposed at the same time, turning off light areas no longer exposed. 

## Screenshots and files 
![imagen](https://user-images.githubusercontent.com/86429314/123310691-a514a800-d526-11eb-9821-e29696b3b813.png)
[Layer10um_Step0.1s_From0.8sTo1.6s.zip](https://github.com/sn4k3/UVtools/files/6711250/Layer10um_Step0.1s_From0.8sTo1.6s.zip)
[photon mono se-en-v0.0.4.pdf](https://github.com/sn4k3/UVtools/files/6711257/photon.mono.se-en-v0.0.4.pdf)

## Additional context
As a reference, the default R_E_R_F test of Anycubic creates a layer for a normal exposure time (1 second for the example), and then, every 0.4 seconds, turns off the area for the object no longer to be exposed (see manual attached, page 48). 

Attached file created, manual of Photon Mono SE and screenshot of layers

**Comment by sn4k3** [comment]
The feature **'Do not perform the lifting sequence fo layers with same Z positioning'** and **'Also set light-off delay to zero'** doesn't work on most printers, in fact they are only valid for GCoded printers. That is a firmware limitation and they can never be 0 as firmware cap the value between a **min** and **max** value, so you can put 0 or 0.1 but firmware will constain that inside a safe value, nothing we can do to change that.
Also the options have tooltips, if you stand still the mouse cursor it will tell you some more information about the options.
As it have no effect, checking that or both will not have a negative impact in the test, but as not supported i recommend to keep those disabled...

RERF file is a special file which firmware interprets and print in a different way, also anycubic printers use a fake AA to produce what you see with the RERF where sections show up and go black, while UVtools can produce the same thing using 'Multiple brightness' i don't recommend them because you need to do some calculations to know the correct AA value, since printer firmware have 8 or 16 levels.

If your objective is spare time, won't. Tests are fast to run and there's no point in ruin the test just to win a few minutes. If you really want to win some speed, reduce base height to 0.3mm and features to 0.5mm for example.
