### ISSUE TITLE
[FEATURE REQUEST]  please add option to choose ctb version. 

### ISSUE THREAD

**Issue by sjhan12** [sn4k3/UVtools#468]
Hi Tiago

I have one suggestion. 

In UVtoolsCmd.exe, please put a option to choose cbt version. 
 
For unencrypted ctb format, UVtoolsCmd.exe convert <input file name> cbt 3 <output file name> and for encrypted ctb format, UVtoolsCmd.exe  convert <input file name> cbt -1 <output file name>

That would make UVtoolsCmd.exe much easy to use. 

Thank you for the great program. 

Sangjo

**Comment by sn4k3** [comment]
That already exists.
Each command have it own flags, to know them just do: `UVtoolsCmd.exe thecommand /?`

![image](https://user-images.githubusercontent.com/113281/165102763-afdc2159-3a85-435d-9071-9a9918b4ba59.png)

So all you need is: `UVtoolsCmd.exe convert -v 4 yourfile.from Chitubox yourfile.ctb`
Since .ctb extensions exists on two distinct classes/formats you need to strict tell the class name, which you can consult here: https://github.com/sn4k3/UVtools/tree/master/UVtools.Core/FileFormats

For ctb encrypted: `UVtoolsCmd.exe convert yourfile.from CTBEncrypted yourfile.ctb`

**Comment by sjhan12** [comment]
Great!

I didn't see it. Thank you for letting me know.
