### ISSUE TITLE
[BUG] Updating removing taksbar shortcut (WIN11)

### ISSUE THREAD

**Issue by hugoalves6** [sn4k3/UVtools#546]
## System
 - OS: Windows 11 

## Describe the bug
In all versions the same append, after installing the update (at least on Windows 11), the taskbar shortcut gets an error has if it was an empty shortcut.
I don't know if the developer knows this mini bug or not, but it's a bit pain, to go to installation folder and drag a new shortcut to the taskbar every time the user updates the program.

I'm Portuguese, and I used my windows in my main language, but i have a screenshot of the error it returns to me:
[Error Image in Portuguese Language](https://hugofalves.pt/screenshots/20220830214100254.png)

Best regards,
Thank you for your hard work.

**Comment by sn4k3** [comment]
That's strange, but the cause is because everytime UVtools upgrades on Windows it get uninstalled first, that's because upgrading without install don't work so well. Since path is the same shortcut should survive but looks like not.
Maybe instead of task the UVtools.exe directly you can create a shortcut, link to UVtools.exe and pin to task?

**Comment by hugoalves6** [comment]
I've tried that, but it does the same thing.

I think i didn't say it but i cannot drag the exe to the taskbar, i have to open the app, and then right click it and select add to taskbar, the shortcut doesn't allow to drag & drop to taskbar either.

After the update is done, i check the address of the taskbar shortcut, and its the same, everything in the proprieties is going to the correct file and folder, that is why I think it's a very weird behavior.

**Comment by sn4k3** [comment]
Can't find a way to fix this with current installer. It looks like Win11 annoyance.
Also this wix don't support pin to taskbar or start without extra .exe packed with UVtools.

Your best bet is pin a shortcut that links cmd instead of UVtools and call UVtools from cmd command, eg:

`C:\Windows\System32\cmd.exe /c start "" "C:\Program Files\UVtools\UVtools.exe"`

![NVIDIA_Share_2022-08-31_22-22-11](https://user-images.githubusercontent.com/113281/187787413-708485e4-bbe0-48a5-9be1-09c4cbf27960.png)

**Comment by hugoalves6** [comment]
Ok thx for that help, hope you find someway to fix it in future.

Best regards
