### ISSUE TITLE
[BUG] Islands detected when there is no island

### ISSUE THREAD

**Issue by eried** [sn4k3/UVtools#71]
I think this is because the gray pixels from Chitubox, like before. But I tried playing with the thresholds without success

![image](https://user-images.githubusercontent.com/1091420/95669294-9300fe00-0b7f-11eb-8c17-5f0a30dde1c2.png)

**Comment by sn4k3** [comment]
That is maybe a resin trap, selected island shows 16 pixel, but on view is way more pixels. Please confirm that, otherwise send me the file for inspection

**Comment by eried** [comment]
Oh you are right! I was wondering why the islands were not repaired, but it was because the next layer was "detected" after the repair so I was just confused with resin traps.

**Comment by eried** [comment]
(Thanks) 

question -> any reason to limit the "removed island max pixels" numericupdown to 255?

**Comment by sn4k3** [comment]
Islands are Yellow, traps are orange but you can configure colors to avoid this.
Also you can hold CTRL and click on a issue on image to go to it on list
About your question, 255 is already a high value of pixels to remove, that is a big mass and should be supported instead of removed, 255px is +/- 13mm and so is dangerous to process automatic. If you want to remove big masses manual is the way to go
