### ISSUE TITLE
[Bug] "Wait time before cure" suggestions not applying properly on CBDDLP

### ISSUE THREAD

**Issue by mbrittsess** [sn4k3/UVtools#715]
### System

```Text
UVtools v3.13.4 X64
Operative system: Microsoft Windows 6.1.7601 Service Pack 1 X64
Processor: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
Processor cores: 8
Memory RAM: 9.84 / 31.96 GB
Runtime: win7-x64
Framework: .NET 6.0.16
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100%
    WA: 1920 x 1080    UA: 1920 x 1080
2: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1050    UA: 1920 x 1050


Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: _LeadBender3.cbddlp [Version: 4] [Class: ChituboxFile]
```

### Printer and Slicer

- Printer: Elegoo Mars
- Slicer: Chitubox 1.9.4

### Description of the bug

When I open a file without wait-before-cure behavior, I receive a "suggestion" to apply some wait time to bottom and normal layers, and also to add a blank first layer to compensate for an error in the Mars firmware. All of these settings are enabled in the suggestion configuration. I see the suggestion as:
> Wait time before cure of 0/0s is out of the recommended 15/2s

I apply the recommended suggestion and save the file under a new name.

If I then open that file, there is no blank first layer. Additionally, wait-before-cure has not been applied for bottom layers; there is still a suggestion which now reads:
> Wait time before cure of 0/2s is out of the recommended 15/2s

Note that there is now a 2-second wait-before-cure time on normal layers, but not on bottom layers!

One of the two reasons I installed UVtools in the first place was to automate the creation of this blank layer (Chitubox can now add this wait time itself, although not separately for bottom and normal layers, but the Mars ignores this for the first layer regardless), so UVtools claiming that it will do it and then not actually doing it is quite frustrating.

### How to reproduce

I open the file exported from Chitubox, see the suggestion:
![image](https://github.com/sn4k3/UVtools/assets/44958514/6d5c67bb-711b-44aa-a60a-4d6e9dfa247e)

I check the settings for this kind of suggestion, everything looks good:
![image](https://github.com/sn4k3/UVtools/assets/44958514/e7d1b129-0a7f-47e0-b956-eb535276badb)

I apply the setting:
![image](https://github.com/sn4k3/UVtools/assets/44958514/f9adb696-bcf7-44f6-a10e-7f15074aa40e)

Save the file under a new name:
![image](https://github.com/sn4k3/UVtools/assets/44958514/9ddba116-b9b5-4e58-b0c1-2e6978d4a3d7)

Let's reload/reopen the new file from scratch:
![image](https://github.com/sn4k3/UVtools/assets/44958514/abdcfb0a-345f-41b6-985f-c663919cca40)

![image](https://github.com/sn4k3/UVtools/assets/44958514/ce9f9840-b1d0-4347-97d0-19b5ea01cc9e)

Still no blank first layer, and now the suggestion tab is showing that the 15s bottom-layer off-time wasn't applied, although the 2s normal-layer off-time was:
![image](https://github.com/sn4k3/UVtools/assets/44958514/76c07f45-a458-43c2-b8a5-d2b30ddb081d)

### Files

[ExampleFiles.zip](https://github.com/sn4k3/UVtools/files/11584130/ExampleFiles.zip)
I have included both the original file as exported from Chitubox, as well as the same file with *only* the wait-before-cure suggestion applied.

**Comment by sn4k3** [comment]
cbddlp is a very old and limited format, pior to Wait time ever exists and so your printer does not know what wait time is. Instead, is able to do LightOff delay. To further the problem your file is output in version 4 which your printer firmware stagnates on version 2! And then all features of v3-v4 are not available to the printer, that's because you use the most recent chitubox and they are not good enough to care about old printers and set conditions to set the correct version depending on printer, instead they always set most recent version even if printer don't support it.

Lychee allow you to set the version but also constrain to which is correct. Chitubox you are tied unless you revert back some version where it output v2 for that format but come at downside of older and worst software.

**My advice:** Change for Lychee, Tango or PrusaSlicer with my profiles.

If you want to keep chitubox, UVtools sanitize version given the file format BUT requires a full encode. Here the workflow:

1. Slice on Chitubox
2. Open in UVtools
3. Go pixel editor, draw a single black pixel on black background and hit apply 
4. Save file (The pixel draw flag file for a full encode, saving will sanitize and downgrade your file to V2!)
5. From this on apply suggestions and resave file

You will also notice that Wait time AFTER cure suggestion will be gone, because v4 supports but v2/v3 won't but it doesn't matter anyway because your printer will never support that.

Important notes:

1. LightOff delay is not absolute wait time and may have error big or small.
2. It will only affect global bottom and normals, no per layer delay as printer don't support it
3. No blank layer will be created as the format is not able to nor required for that the format.

Overall that format is very limited and UVtools always do what it can but all rely on your printer firmware and format capabilities
