### ISSUE TITLE
[BUG] New unsupported islands after repair

### ISSUE THREAD

**Issue by Angelus1981** [sn4k3/UVtools#74]
**Describe the bug**
After using the repair tool I have quite a lot issues that within a support there are layers without pixels.

**To Reproduce**
I use Chitubox 1.7.0 as slicer for my Elegoo Saturn. The   file is saved as .ctb file.

**Expected behavior**
There shouldn't be empty layers within a support after using the repair function

**Screenshots**

**Files**
I do not know how to upload files to Github but I can provide a file where I have the issue

**Desktop (please complete the following information):**
 - OS: Win 10 64 bit

**Comment by sn4k3** [comment]
Most likely that are caused by wrong configuration under your specific use.
Can you post a screenshot of you tool repair window with advanced options showing?

**Comment by Angelus1981** [comment]
Hi, Sorry for the late reply.

please find the screenshot attached. I only changed one value since this one seems to be too high for my support settings that I typically use without problems. But I had the described issue also with the standard settings that come with the installation.
![Settings](https://user-images.githubusercontent.com/72758512/96227035-c7b3f180-0f93-11eb-86f6-03999c68ae59.jpg)


Please find also 3 screenshots of the issue with the posted settings. 

Before using the fixing functions e.g. it shows 4 issues in layer 936 as seen in screenshot:
<img width="1920" alt="936_before_fix" src="https://user-images.githubusercontent.com/72758512/96227115-e6b28380-0f93-11eb-97a8-8fb99370c729.png">

After fixing 1 issue is shown on a completely different location where suddently one layer for a support is emtpy. I made a picture of the layer mentioned in the issue list:
![936_fixed](https://user-images.githubusercontent.com/72758512/96227165-ffbb3480-0f93-11eb-874e-4492a5664aec.jpg)

ans the layer below which is emtpy, causing the issue.
![935_fixed](https://user-images.githubusercontent.com/72758512/96227171-021d8e80-0f94-11eb-9aaa-09fcd7abaf3b.jpg)

So before using the issue fixing tool layer 935 didn't had any issues there. Hope that helps.

**Comment by sn4k3** [comment]
Ok so the title and main writing of your problem is wrong and lead me in error. 
You were refering empty layers, that is layers with 0 white pixels in total (all black), and that's not your case.
I've edit your title to correct the real discuss here.

UVtools never create new masses on repair, at maximum he increase brightness of already existing pixels or expand to bound two joins.
To confirm this open the file without repair and go to that region were you have that "new" island, hover with mouse using Control, look on bottom status bar and see the "B:" value, if anything greater than 0, than thats the problem. 
Please confirm this.

Also if you want attach your file to i check, via wetransfer for example

**Comment by Angelus1981** [comment]
Sorry if heading was misleading. 
I tried to do what you wrote but I think it is fine that the B value is higher than 0 since this means there are pixels which sould be since there should be the support.

I now proceeded with version v8.5.0 and face the same issue but surprisingly on a different layer now in the same model.

So opened the file again and checked layer 949 and 948/947. There is no island since the support is available in both layers.
![949_after_opening](https://user-images.githubusercontent.com/72758512/96290987-c14f6500-0fe7-11eb-95bb-7d2fbe7c1948.jpg)
![948_after_opening](https://user-images.githubusercontent.com/72758512/96290992-c3b1bf00-0fe7-11eb-81fe-2a89e351fd09.jpg)
![947_after_opening](https://user-images.githubusercontent.com/72758512/96290999-c4e2ec00-0fe7-11eb-98eb-71abe25e69a4.jpg)

I run the "issues" operation to identify issues. The tool identifies the pixels from the support as error (pixels in layer 948 still there)
<img width="1920" alt="949_issue_identified" src="https://user-images.githubusercontent.com/72758512/96291268-17bca380-0fe8-11eb-9a54-c58d8ee421e2.png">
<img width="1920" alt="948_still_pixels" src="https://user-images.githubusercontent.com/72758512/96291425-4c305f80-0fe8-11eb-8901-2b52c70f9150.png">

After repairing with the default settings from clean installation there is suddenly no pixels in the area of the support in layer 948 and some layers below (not the complete layer is empty only the region of the support). So it seems the tool deleted pixels during repair operation.

![949_After_repair](https://user-images.githubusercontent.com/72758512/96292476-99f99780-0fe9-11eb-90aa-acc7d97908d8.jpg)
![948_After_repair](https://user-images.githubusercontent.com/72758512/96292487-9e25b500-0fe9-11eb-874a-ecfd737bfb5d.jpg)
![947_After_repair](https://user-images.githubusercontent.com/72758512/96292501-a120a580-0fe9-11eb-9750-ef67c0ad8cf0.jpg)


Settings (default as per installation):
![Settings](https://user-images.githubusercontent.com/72758512/96289766-e17e2480-0fe5-11eb-839a-73ad51bba008.jpg)
![repair_options](https://user-images.githubusercontent.com/72758512/96289770-e2af5180-0fe5-11eb-86ae-12b91594fe17.jpg)



I also sent you the file to the email given in your profile via wetransfer. Please have a look.

**Comment by sn4k3** [comment]
Ok your problem are related to settings.

It is a island because bellow is unsafed supported, please read this thread: https://www.facebook.com/groups/uvtools/permalink/341571073619069?comment_id=342323286877181

About islands got remove is due new function, recursive removal, it remove islands below x pixel count, so when you run repair it will remove this island, then check upstair and verify same condition up remove everything that match that criteria.
If you want to disable this, set Revome islands equal or smaller than: 0 px.

UVtools is a generic program so the defaults will never match everyone, you must tune it for your use. Take your time to read the tooltips that are present on functions / labels / boxes.

Also keep in mind you dont have to clear all islands, a issue doesn't mean a real problem, it's more a warning that you must deal with. Try to clean all issues or lower safe values on uvtools is a bad pratice, you should decide if remove/fix a island is really needed.
Again: Just because you have 1 pixel supporting a bunch more, that doesnt mean is well supported, so UVtools will always report them as unsafe

**Comment by Angelus1981** [comment]
Ok I will check with the next file that I will work on. I will give feedback ASAP

**Comment by sn4k3** [comment]
Settings based
