### ISSUE TITLE
Creality Halot One - Error with Height and Width of the screen (incorrect ratio)

### ISSUE THREAD

**Issue by CoralieMango3D** [sn4k3/UVtools#753]
### System

```Text
UVtools v3.15.1 X64
Operative system: Microsoft Windows 10.0.22621 X64
Processor: AMD Ryzen 7 6800H with Radeon Graphics         
Processor cores: 16
Memory RAM: 8.85 / 15.25 GB
Runtime: win10-x64
Framework: .NET 6.0.18
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 125% (Primary) (On this)
    WA: 1920 x 1020    UA: 1536 x 816
2: 1920 x 1080 @ 100%
    WA: 1920 x 1032    UA: 1920 x 1032

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: base_V3 (1).cxdlp [Version: 3] [Class: CXDLPFile]
```

### Printer and Slicer

- Printer: Creality Halot One
- Slicer: Lychee Slicer 
![halot one ratio error uvtools](https://github.com/sn4k3/UVtools/assets/122971512/e7dd8bda-3ae3-4d09-908a-2d1ecd495300)

### Description of the bug

When our Lychee Slicer user dumps the files into UVTOOLS (to check for errors) it says there is an error with the Height and Width of the screen (incorrect ratio)

These values are correctly configured in Lychee Slicer but the files in UVTOOLS have the sizes of the scree
![halot one ratio error uvtools](https://github.com/sn4k3/UVtools/assets/122971512/a3702b91-23c3-4258-a14b-77e01c84577a)
n inverted.

### How to reproduce

1. Open file sliced with Lychee Slicer for Creality Halot One
2. Error message pops-up 

### Files

[Halot one ratio error.zip](https://github.com/sn4k3/UVtools/files/12524979/Halot.one.ratio.error.zip)

**Comment by sn4k3** [comment]
> So we have to modify Lychee Halot One configuration to set "Width (X axis)" to "81"? 

No. On the UI they have swap the values of X with Y and when writing to file they swap them again, so X value goes to Y and vice-versa, with exception of the LCD values. I don't understand the logic they are using (Incorrect values on UI and then fixing on file write but forgot to swap the LCD values) there is a mess there. 

> I have never had any printing problems

Because LCD information (metric size) on file is irrelevant to the printer, Printer only validates the resolution (pixel size) info which is absolute, and so the lcd metadata can be set to whatever you want and it will still print (Printer trust the file is sliced with correct pixel ratio).
UVtools otherwise rely on correct LCD size to do some calculations and generate pixels given metric sizes. For UVtools is important but still not required as soon you don't use any tool that rely on that lcd info, that's why it warns and allow you to ignore. Anyway is a fail-safe check that should not be ignored.

See the following 3 slicers configurations for Halot, you will notice only Lychee does it differently (But again they swap them on file write but forget about LCD):

![image](https://github.com/sn4k3/UVtools/assets/113281/c116c5ff-1da6-4da1-a000-70352877dacf)
![image](https://github.com/sn4k3/UVtools/assets/113281/de8454de-ba38-4a4d-b467-53dcdb15ed84)
![image](https://github.com/sn4k3/UVtools/assets/113281/52d2a257-31ee-4726-8d16-bc196751b7d6)
